### ISSUE TITLE
Scoop Package

### ISSUE THREAD

**Issue by graphixillusion** [lcomrade/horizon#1]
What about to add this software to scoop repo too?

https://scoop.sh/

**Comment by lcomrade** [comment]
It will be available with the next release (v0.8). I just created a [card](https://github.com/lcomrade/horizon/projects/7#card-67937528).

**Comment by lcomrade** [comment]
I made a Scoop manifest. But adding it to the main bucket would be too long and not easy. So I made my [own bucket](https://github.com/lcomrade/ScoopBucket). The software version will be updated in this bucket at the time of release.

In order to use this bucket, add it: `scoop bucket add lcomrade https://github.com/lcomrade/ScoopBucket`

Now you can install software from it as usual: `scoop install horizon`
